export type EmailPurchase = { title: string; license: string };
const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);

export function purchaseEmail(origin: string, items: EmailPurchase[], test: boolean) {
  const url = new URL("/library", origin).href;
  const logo = new URL("/brand/email-logo.png", origin).href;
  const title = test ? "Your test purchase is ready" : "Your sounds are ready";
  const rows = items.map(item => `<tr><td style="padding:18px 0;border-bottom:1px solid #34362f"><strong style="color:#f0eee3;font-size:16px">${escape(item.title)}</strong><br><span style="color:#b1b3a5;font-size:13px">${escape(item.license)}</span></td></tr>`).join("");
  return {
    subject: `${title} — Lost Files Library`,
    text: `LOST FILES LIBRARY\n\n${title}\n\n${items.map(item => `${item.title} — ${item.license}`).join("\n")}\n\nDownload your files: ${url}\nSign in with the same account used at checkout. Your purchases stay in My Library for future downloads.\n${test ? "This was a test purchase. No real money was charged.\n" : ""}`,
    html: `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title></head><body style="margin:0;background:#10120f;font-family:Arial,Helvetica,sans-serif;color:#f0eee3"><div style="display:none;max-height:0;overflow:hidden">Your purchased sounds are waiting in My Library.</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#10120f"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="560" cellpadding="0" cellspacing="0" style="width:100%;max-width:560px;border:1px solid #34362f;background:#171a15"><tr><td style="padding:32px"><img src="${escape(logo)}" width="64" height="64" alt="Lost Files logo" style="display:block;border:0;margin-bottom:20px"><div style="font-family:Courier New,monospace;letter-spacing:2px;font-size:12px;color:#c5a66c">LOST FILES / LIBRARY</div><h1 style="font-size:30px;line-height:1.2;font-weight:500;margin:24px 0 12px">${title}.</h1><p style="color:#b1b3a5;line-height:1.6">Thank you for making room for a new sound. Your purchase is saved in your personal library.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0">${rows}</table><table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:28px"><tr><td bgcolor="#c5a66c" style="padding:16px 24px"><a href="${escape(url)}" style="color:#11120f;font-weight:bold;text-decoration:none;font-size:15px">Download your files →</a></td></tr></table><p style="font-size:13px;color:#b1b3a5;line-height:1.7;margin-top:24px">Sign in with the same account used at checkout. You can return to My Library whenever you need your files.</p>${test ? '<p style="font-size:12px;color:#c5a66c">TEST PURCHASE · No real money was charged. Demo files are labeled in your library.</p>' : ""}<p style="font-size:12px;color:#b1b3a5;word-break:break-all">Button not opening? <a href="${escape(url)}" style="color:#c5a66c">${escape(url)}</a></p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #34362f;font-family:Courier New,monospace;font-size:10px;letter-spacing:1px;color:#b1b3a5">INDEPENDENT SOUND. WORLDWIDE.<br><br>LOST FILES LIBRARY</td></tr></table></td></tr></table></body></html>`,
  };
}
